filebeat.registry_file: /usr/share/filebeat/data/registry

filebeat.config.prospectors:
#prospectors dynamically loaded from the sub-directory
  path: ${path.config}/prospectors.d/*.yml
  reload.enabled: false

filebeat.modules:
- module: system
  syslog:
    enabled: true
    var.paths: ["/var/log/host/system.log*"]

- module: nginx
  access:
    enabled: true
    var.paths: ["/var/log/nginx/access.log*"]
  error:
    enabled: true
    var.paths: ["/var/log/nginx/error.log*"]

#- module: mysql
#  error:
#    var.paths: ["/var/log/mysql/error.log*"]
#  slowlog:
#    var.paths: ["/var/log/mysql/mysql-slow.log*"]


output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"