version: '3.7'

services:
    # Nginx server for static frontend 
    nginx:        
        build:
            context: ../
            dockerfile: nginx.dockerfile
        container_name: nginx_docker
        restart: unless-stopped
        ports:
          - 80:80
          - 443:443
        volumes:
          - ../frontend/:/var/app/frontend/
          - ./conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
          - /etc/letsencrypt/:/etc/letsencrypt/
        depends_on:
          - uwsgi

    # uWSGI server for backend 
    uwsgi:
        build:
            context: .
            dockerfile: uwsgi.dockerfile
        container_name: uwsgi_docker
        restart: unless-stopped
        ports:
          - 8001:8001
        volumes:
          - ../backend/:/var/app/backend/
          - ./conf/uwsgi.ini:/var/conf/uwsgi.ini
          - /var/log/uwsgi.log:/var/log/uwsgi.log
          - /var/conf/ihse.ini:/var/conf/ihse.ini
        depends_on:
            - database

    # PostgeSql server for backend 
    # TODO
    database:
        image: postgres:12.1
#        build:
#            context: .
#            dockerfile: database.dockerfile
        container_name: database_docker
        restart: unless-stopped
        ports:
          - 5431:5431
        volumes:
          - /var/lib/postgresql/data:/var/lib/postgresql/data/pgdata
        environment:
            POSTGRES_DB: root
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            PGDATA: /var/lib/postgresql/data/pgdata
        command: -p 5431
