version: '3.7'
    
services:
    # Nginx server for static frontend 
    nginx:        
        build:
            context: ./nginx/
            dockerfile: nginx_local.dockerfile
        container_name: nginx_docker_local
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ../frontend/:/var/app/frontend/
            - ../local_run/log/nginx:/var/log/nginx/
        depends_on:
            - uwsgi

    # uWSGI server for backend 
    uwsgi:
        build:
            context: ./uwsgi/
            dockerfile: uwsgi.dockerfile
        container_name: uwsgi_docker
        restart: unless-stopped
        volumes:
            - ../backend/:/var/app/backend/
            - ../local_run/ihse/conf/:/var/conf/ihse/
            - ../local_run/log/uwsgi:/var/log/uwsgi
        depends_on:
            - database

    # PostgreSQL server for backend
    database:
        image: postgres:12.1
#        build:
#            context: ./postgres
#            dockerfile: postgres.dockerfile
        container_name: database_docker
        restart: unless-stopped
        ports:
            - 5432:5432
        volumes:
            - ../local_run/postgres/data:/var/lib/postgresql/data/pgdata
            - ../local_run/postgres/exports:/var/lib/postgresql/exports/
            - ./postgres/templates/example.sql:/docker-entrypoint-initdb.d/example.sql  # Change for others docker-compose
        environment:
            POSTGRES_DB: ihse
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            PGDATA: /var/lib/postgresql/data/pgdata
