name: Docker Image Build and Artifacting

on:
    push:
        branches:
            - develop

jobs:

    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Build the Docker image
              run: docker-compose build ./docker --file docker-compose.yml > build.log

            - name: Upload artifact
              uses: actions/upload-artifact@v1.0.0
              with:
                  name: build.log
                  path: .
