name: minimization
# Run tests for javascript for any push.

on:
    push:
        branches:
            - master
            - release

jobs:
    minimization:
        runs-on: [ubuntu-latest]

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: CSS minimization
              working-directory: ./frontend
              run: |
                  npm install
                  npm install uglifycss -g

                  ls -la styles/
                  ls -la components/styles/

                  for fileName in `ls ./styles/*.css` `ls ./components/styles/*.css`; do
                      uglifycss $fileName --output $fileName
                  done

                  ls -la styles/
                  ls -la components/styles/

            - name: JS minimization
              working-directory: ./frontend
              run: |
                  npm install
                  npm install uglify-es -g

                  ls -la scripts/
                  ls -la components/scripts/

                  for fileName in `ls ./scripts/*.js` `ls ./components/scripts/*.js`; do
                     uglifyjs $fileName --output $fileName
                  done

                  ls -la scripts/
                  ls -la components/scripts/

            - name: HTML minimization
              working-directory: ./frontend
              run: |
                  npm install
                  npm install html-minifier -g

                  ls -la .
                  ls -la components/

                  for fileName in `ls ./*.html` `ls ./components/*.html`; do
                     html-minifier $fileName --output $fileName --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-css true --minify-js true
                  done

                  ls -la .
                  ls -la components/
