name: pystyle

on:
    push:
        branches:
            - master
            - release

jobs:
  styleCheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
      
    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Lint with flake8
      working-directory: ./backend
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 main.py --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 main.py --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

        flake8 sql.py --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 sql.py --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

    - name: Test with mypy
      continue-on-error: true
      working-directory: ./backend
      run: |
        pip install mypy
        mypy main.py
        mypy sql.py

    - name: Test with pycodestyle
      working-directory: ./backend
      run: |
        pip install pycodestyle
        pycodestyle main.py --max-line-length=120
        pycodestyle sql.py --max-line-length=120
