name: pytests
# Run tests for python for any push.

on:
    push:
        tags:
            - '!refs/tags/*'
        branches:
            - '*'

jobs:
    run_tests:
        runs-on: [ubuntu-latest]
        steps:
            # Checkout to code
            - uses: actions/checkout@master
            # Setup python
            - uses: actions/setup-python@v1
              with:
                python-version: '3.7'
                architecture: 'x64'

            # Install requirements
            - name: Install requirements
              run: pip install -r backend/requirements.txt

            - name: Run tests
              run: coverage run tests/tmp.py
            - name: Tests report
              run: coverage report
