name: pytests
# Run tests for python for any push.

on:
    push:
        branches:
            - master
            - release

jobs:
    runTests:
        runs-on: [ubuntu-latest]
        steps:
            # Checkout to code
            -   uses: actions/checkout@v2
            # Setup python
            -   uses: actions/setup-python@v1
                with:
                    python-version: '3.7'
                    architecture: 'x64'

            # Install requirements
            -   name: Install requirements
                run: pip install -r backend/requirements.txt

            # Testing with counting codecoverage
            #            - name: Run tests
            #              run: |
            #                pip install pytest
            #                pip install coverage
            #                coverage run -m pytest tests/
            #            - name: Tests report
            #              run: coverage report

            # Testing with counting codecoverage
            -   name: Generate coverage report
                run: |
                    pip install pytest
                    pip install pytest-cov
                    pytest backend/tests/ --cov=./ --cov-report=xml
            -   name: Upload coverage to Codecov
                uses: codecov/codecov-action@v1
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    file: ./coverage.xml
                    flags: unittests
                    name: codecov-umbrella
                    yml: ./codecov.yml
                    fail_ci_if_error: true